### ISSUE TITLE
TFOXML is not documented

### ISSUE THREAD

**Issue by zbx1425** [leezer3/OpenBVE-Documentation-Hugo#17]
The way of applying a TFO XML file is not documented in documentation_hugo/en/routes/csv.html.

**Comment by s520** [comment]
There are several other undocumented features.
First, we will need to list the undocumented features.

**Comment by leezer3** [comment]
I *think* most are here:
https://github.com/leezer3/OpenBVE/wiki/Compatibility-Notes

**Comment by BPI-919** [comment]
I am afraid, that this feature (**(1)TFOXML**) has not documented yet, and the **(2)Options.ReversedDirection** command is also missing in the Developer Documentation of the .csv Route files, as well.
Unfortunately the Include, Object, Sound and StateChangeSound **(3)Sections are also not shown** under the Contents \ Sections menu as a list in the Developer Documentation of .animated files.
On the first attached picture you can see it. On the second picture you can see, that **(4)new line characters are missings** between the ScaleXFunction, ScaleYFunction and ScaleZFunction commands.
![Screenshot_2024-03-01-19-37-17-886_org mozilla firefox](https://github.com/leezer3/OpenBVE-Documentation-Hugo/assets/66689434/84fb2384-bd7b-4f0b-88dc-5f27f1bf1825)
![Screenshot_2024-03-01-19-37-35-734_org mozilla firefox](https://github.com/leezer3/OpenBVE-Documentation-Hugo/assets/66689434/9126b3b0-b0e7-4708-adef-a21c1528af8d)

@leezer3 : Can you fix them in the future?

Thanks in advance,
BPI-919 Andris (Andras Csolakov)

**Comment by leezer3** [comment]
The TFOxml documentation is here:
https://openbve-project.net/documentation_hugo/en/routes/xml/trackfollowingobject.html

Seems to have been missed from the main CSV page though, so have added that.

The newlines are odd, some sort of whitespace issue, but that should now be OK.

Will see about the rest over the next day or two.

**Comment by BPI-919** [comment]
Thanks for fixing the (1).TFOxml and the (4)new line characters' issue.

Are you planning to implement the other 2 "requests" ? (Options.ReversedDirection and showing the [Include], [Object], [Sound], [StateChangeSound] sections as the items of a list)

Thanks in advance and Regards,
Andras

**Comment by leezer3** [comment]
Added, forgot those,
