### ISSUE TITLE
Please update the bot

### ISSUE THREAD

**Issue by s520** [leezer3/OpenBVE-Documentation-Hugo#18]
Please update the bot on Heroku.
https://github.com/s520/txgh-js-bot/tree/master

I modified the bot so that it does not create an empty commit like the one below.
https://github.com/leezer3/OpenBVE-Documentation-Hugo/commit/b693949c5d62284f0268a3f062a5d4a79713e150

Transifex's webhooks with the same content were executed multiple times.
Therefore, check and filter SHA1 of GitHub file.

**Comment by leezer3** [comment]
I think that's done- See what happens now. (Build was a little slow, but it's only changes in the main js file)

I believe I added you to the people who can get into Heroku when we were trying to get this working in the first place.

**Comment by leezer3** [comment]
Incidentally from the build log:
```
-----> Build

       

-----> Pruning devDependencies

       removed 843 packages and audited 271 packages in 9.408s

       found 1 moderate severity vulnerability

         run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by s520** [comment]
Yes.
I have authority, but thought I should get confirmation from you.
I will update it.

**Comment by s520** [comment]
I close this issue because my original purpose was fulfilled.
